# Generated by Django 5.2.8 on 2025-11-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main', 'tag__name'], 'verbose_name': 'Тематика Cтатьи', 'verbose_name_plural': 'Тематики Cтатьи'},
        ),
    ]
